[workspace]
resolver = "2"
members = [
    "src/types-and-values",
    "src/control-flow-basics",
    "src/tuples-and-arrays",
    "src/references",
    "src/user-defined-types",
    "src/pattern-matching",
]
